In [1]:
import pandas as pd
df = pd.read_csv("bridges.csv")

I'm going to make an assumption that bridges cannot have the length with value NaN or na. I will drop the bridges with length NaN.

In [2]:
df

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
0,E1,M,3.0,1818,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
1,E2,A,25.0,1819,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,E3,A,39.0,1829,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
3,E5,A,29.0,1837,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
4,E6,M,23.0,1838,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,E84,A,24.0,1969,HIGHWAY,870.0,6.0,G,THROUGH,STEEL,MEDIUM,F,ARCH
104,E91,O,44.0,1975,HIGHWAY,3756.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
105,E90,M,7.0,1978,HIGHWAY,950.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
106,E100,O,43.0,1982,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN
107,E109,A,28.0,1986,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN

In [3]:
df.isna().sum()

Id           0
river        0
location     1
erected      0
purpose      0
length      27
lanes       16
clear-g      2
t-or-d       6
material     2
span        16
rel-l        5
type         2
dtype: int64

In [4]:
df[df['length'].isna()]

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
0,E1,M,3.0,1818,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
2,E3,A,39.0,1829,AQUEDUCT,NaN,1.0,N,THROUGH,WOOD,NaN,S,WOOD
4,E6,M,23.0,1838,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
8,E10,A,39.0,1848,AQUEDUCT,NaN,1.0,N,DECK,WOOD,NaN,S,WOOD
10,E12,A,39.0,1853,RR,NaN,2.0,N,DECK,WOOD,NaN,S,WOOD
12,E13,A,33.0,1856,HIGHWAY,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
13,E15,A,28.0,1857,RR,NaN,2.0,N,THROUGH,WOOD,NaN,S,WOOD
19,E21,M,16.0,1874,RR,NaN,2.0,NaN,THROUGH,IRON,NaN,NaN,SIMPLE-T
22,E24,O,45.0,1878,RR,NaN,2.0,G,NaN,STEEL,NaN,NaN,SIMPLE-T
23,E25,M,10.0,1882,RR,NaN,2.0,G,NaN,STEEL,NaN,NaN,SIMPLE-T
24,E27,A,39.0,1883,RR,NaN,2.0,G,THROUGH,STEEL,NaN,F,SIMPLE-T
26,E30,A,31.0,1884,RR,NaN,2.0,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
29,E32,A,30.0,1887,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
33,E36,O,45.0,1890,HIGHWAY,NaN,2.0,G,THROUGH,IRON,SHORT,F,SIMPLE-T
35,E38,M,17.0,1891,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
37,E39,A,25.0,1892,HIGHWAY,NaN,2.0,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
39,E40,M,22.0,1893,HIGHWAY,NaN,2.0,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
40,E41,M,11.0,1894,HIGHWAY,NaN,2.0,G,THROUGH,IRON,MEDIUM,F,SIMPLE-T
42,E44,O,48.0,1896,HIGHWAY,NaN,2.0,G,THROUGH,STEEL,LONG,F,SUSPEN
49,E94,M,13.0,1901,RR,NaN,2.0,G,THROUGH,STEEL,LONG,F,SIMPLE-T
59,E56,M,23.0,1909,HIGHWAY,NaN,NaN,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
63,E107,A,39.0,1914,RR,NaN,NaN,G,NaN,STEEL,NaN,F,NIL
69,E65,A,30.0,1921,WALK,NaN,NaN,G,THROUGH,STEEL,NaN,F,SUSPEN
91,E97,Y,52.0,1945,HIGHWAY,NaN,NaN,G,THROUGH,STEEL,MEDIUM,S,ARCH
92,E96,Y,51.0,1945,RR,NaN,NaN,G,THROUGH,STEEL,MEDIUM,F,SIMPLE-T
106,E100,O,43.0,1982,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN
107,E109,A,28.0,1986,HIGHWAY,NaN,NaN,G,NaN,NaN,NaN,F,NaN

I see that a few bridges have length value NaN already, like ones labeled E1, E3, E6 and so on. By using df[df['length'].isna()] I can visually see all the bridges with length NaN. By using isna() and sum() functions, I see a total of 27 bridges have length with value NaN. I will drop them and make a clean dataframe that only contains bridges with lengths that are in number values.

In [5]:
df_cleaned = df.dropna(subset=['length'])

In [6]:
df_cleaned

,Id,river,location,erected,purpose,length,lanes,clear-g,t-or-d,material,span,rel-l,type
1,E2,A,25.0,1819,HIGHWAY,1037.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
3,E5,A,29.0,1837,HIGHWAY,1000.0,2.0,N,THROUGH,WOOD,SHORT,S,WOOD
5,E7,A,27.0,1840,HIGHWAY,990.0,2.0,N,THROUGH,WOOD,MEDIUM,S,WOOD
6,E8,A,28.0,1844,AQUEDUCT,1000.0,1.0,N,THROUGH,IRON,SHORT,S,SUSPEN
7,E9,M,3.0,1846,HIGHWAY,1500.0,2.0,N,THROUGH,IRON,SHORT,S,SUSPEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,E86,A,33.0,1961,HIGHWAY,980.0,4.0,G,DECK,STEEL,MEDIUM,S-F,CONT-T
102,E85,M,9.0,1962,HIGHWAY,2213.0,4.0,G,DECK,STEEL,LONG,F,CONT-T
103,E84,A,24.0,1969,HIGHWAY,870.0,6.0,G,THROUGH,STEEL,MEDIUM,F,ARCH
104,E91,O,44.0,1975,HIGHWAY,3756.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH
105,E90,M,7.0,1978,HIGHWAY,950.0,6.0,G,THROUGH,STEEL,LONG,F,ARCH

# Cleaning log
Loaded 108 rows; dropped 27 rows left with 81; bridges with NaN length handled by getting dropped because they are not plausible.

Repo Address: https://github.com/yeonghwang-hub/cs82a-portfolio