In [1]:
import sqlite3
import pandas as pd
import seaborn as sns
import scipy
import matplotlib.pyplot as plt

con = sqlite3.connect("customers.db")

cursor = con.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS customers (
    id INTEGER PRIMARY KEY UNIQUE,
    name TEXT,
    city TEXT,
    age INTEGER
);
""")

In [2]:
pd.read_sql("SELECT * FROM customers", con)

   id    name           city  age
0   1    Ryan    Los Angeles   25
1   2   Jason        Seattle   20
2   3  Claire       New York   33
3   4   Karie         Austin   32
4   5   Jenny  San Francisco   23
5   6   Bryan       New York   40
6   7   Alice          Miami   35
7   8   James        Chicago   28

In [3]:
sql = "INSERT OR IGNORE INTO customers (id, name, city, age) VALUES (?, ?, ?, ?)"

customers_data = [
    (1, "Ryan", "Los Angeles", 25),
    (2, "Jason", "Seattle", 20),
    (3, "Claire", "New York", 33),
    (4, "Karie", "Austin", 32),
    (5, "Jenny", "San Francisco", 23),
    (6, "Bryan", "New York", 40),
    (7, "Alice", "Miami", 35),
    (8, "James", "Chicago", 28)
]

cursor.executemany(sql, customers_data)
con.commit()

In [4]:
pd.read_sql("SELECT * FROM customers", con)

   id    name           city  age
0   1    Ryan    Los Angeles   25
1   2   Jason        Seattle   20
2   3  Claire       New York   33
3   4   Karie         Austin   32
4   5   Jenny  San Francisco   23
5   6   Bryan       New York   40
6   7   Alice          Miami   35
7   8   James        Chicago   28

In [5]:
con.close()

I had to manually connect or make a connection to a db using sqlite, whereas for mysql, you can just use CREATE TABLE command.

Repo Address: https://github.com/yeonghwang-hub/cs82a-portfolio