In [1]:
import pandas as pd
import seaborn as sns
import scipy
import matplotlib.pyplot as plt

df = pd.read_csv("custdata.tsv", sep="\t")
df

,custid,sex,is.employed,income,marital.stat,health.ins,housing.type,recent.move,num.vehicles,age,state.of.res
0,2068,F,NaN,11300,Married,True,Homeowner free and clear,False,2.0,49.0,Michigan
1,2073,F,NaN,0,Married,True,Rented,True,3.0,40.0,Florida
2,2848,M,True,4500,Never Married,False,Rented,True,3.0,22.0,Georgia
3,5641,M,True,20000,Never Married,False,Occupied with no rent,False,0.0,22.0,New Mexico
4,6369,F,True,12000,Never Married,True,Rented,True,1.0,31.0,Florida
...,...,...,...,...,...,...,...,...,...,...,...
995,1411132,F,False,46000,Divorced/Separated,True,Rented,True,1.0,56.0,Florida
996,1411860,F,NaN,5400,Widowed,True,NaN,NaN,NaN,89.0,Pennsylvania
997,1412161,M,True,38500,Married,True,Rented,True,1.0,29.0,Georgia
998,1412971,M,NaN,43400,Married,True,Homeowner free and clear,False,1.0,88.0,Ohio
999,1414286,F,False,20900,Married,False,Rented,False,2.0,36.0,New York

In [2]:
selected_columns = ["income", "num.vehicles", "age"]
corr_subset = df[selected_columns].corr()

In [3]:
corr_subset

                income  num.vehicles       age
income        1.000000      0.139198  0.027429
num.vehicles  0.139198      1.000000 -0.063666
age           0.027429     -0.063666  1.000000

The data has invalid values, so clean it, then produce another correlation matrix.

In [4]:
df_cleaned = df[(df["income"] >= 0)]
df_cleaned

,custid,sex,is.employed,income,marital.stat,health.ins,housing.type,recent.move,num.vehicles,age,state.of.res
0,2068,F,NaN,11300,Married,True,Homeowner free and clear,False,2.0,49.0,Michigan
1,2073,F,NaN,0,Married,True,Rented,True,3.0,40.0,Florida
2,2848,M,True,4500,Never Married,False,Rented,True,3.0,22.0,Georgia
3,5641,M,True,20000,Never Married,False,Occupied with no rent,False,0.0,22.0,New Mexico
4,6369,F,True,12000,Never Married,True,Rented,True,1.0,31.0,Florida
...,...,...,...,...,...,...,...,...,...,...,...
995,1411132,F,False,46000,Divorced/Separated,True,Rented,True,1.0,56.0,Florida
996,1411860,F,NaN,5400,Widowed,True,NaN,NaN,NaN,89.0,Pennsylvania
997,1412161,M,True,38500,Married,True,Rented,True,1.0,29.0,Georgia
998,1412971,M,NaN,43400,Married,True,Homeowner free and clear,False,1.0,88.0,Ohio
999,1414286,F,False,20900,Married,False,Rented,False,2.0,36.0,New York

Removed one row with "income" less than 0 since one cannot have negative income.

In [5]:
df_cleaned = df[(df["age"] < 110)]
df_cleaned

,custid,sex,is.employed,income,marital.stat,health.ins,housing.type,recent.move,num.vehicles,age,state.of.res
0,2068,F,NaN,11300,Married,True,Homeowner free and clear,False,2.0,49.0,Michigan
1,2073,F,NaN,0,Married,True,Rented,True,3.0,40.0,Florida
2,2848,M,True,4500,Never Married,False,Rented,True,3.0,22.0,Georgia
3,5641,M,True,20000,Never Married,False,Occupied with no rent,False,0.0,22.0,New Mexico
4,6369,F,True,12000,Never Married,True,Rented,True,1.0,31.0,Florida
...,...,...,...,...,...,...,...,...,...,...,...
995,1411132,F,False,46000,Divorced/Separated,True,Rented,True,1.0,56.0,Florida
996,1411860,F,NaN,5400,Widowed,True,NaN,NaN,NaN,89.0,Pennsylvania
997,1412161,M,True,38500,Married,True,Rented,True,1.0,29.0,Georgia
998,1412971,M,NaN,43400,Married,True,Homeowner free and clear,False,1.0,88.0,Ohio
999,1414286,F,False,20900,Married,False,Rented,False,2.0,36.0,New York

Removed 7 rows with "age" greater than 110 because it is not realistic.

In [6]:
selected_columns = ["income", "num.vehicles", "age"]
corr_subset_cleaned = df_cleaned[selected_columns].corr()

In [7]:
corr_subset_cleaned

                income  num.vehicles       age
income        1.000000      0.136480  0.006244
num.vehicles  0.136480      1.000000 -0.068378
age           0.006244     -0.068378  1.000000

In [8]:
corr_subset

                income  num.vehicles       age
income        1.000000      0.139198  0.027429
num.vehicles  0.139198      1.000000 -0.063666
age           0.027429     -0.063666  1.000000

Compared to the BEFORE correlation matrix, the CLEANED correlation matrix shows a noticeable change in the age vs income correlation. It gets closer to 0, meaning that there is no linear relationship between the variables. Removed one row with "income" less than 0 since one cannot have negative income. Removed 7 rows with "age" greater than 110 because it is not realistic.

Repo Address: https://github.com/yeonghwang-hub/cs82a-portfolio/tree/main